2020-12-18 18:09:39,165-error-request_util.py[request:169]-ERROR : request error, url: https://www.zhipin.comhttps://www.zhipin.com/gongsi/_zzz_c101281600_iy100504/, error: HTTPSConnectionPool(host='www.zhipin.comhttps', port=443): Max retries exceeded with url: //www.zhipin.com/gongsi/_zzz_c101281600_iy100504/ (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))
2020-12-18 18:12:46,836-error-request_util.py[request:169]-ERROR : request error, url: https://www.zhipin.comhttps://www.zhipin.com/gongsi/_zzz_c101281600_iy100504/, error: HTTPSConnectionPool(host='www.zhipin.comhttps', port=443): Max retries exceeded with url: //www.zhipin.com/gongsi/_zzz_c101281600_iy100504/ (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))
2020-12-18 18:15:35,876-error-request_util.py[request:169]-ERROR : request error, url: https://www.zhipin.comhttps://www.zhipin.com/gongsi/_zzz_c101281600_iy100504/, error: HTTPSConnectionPool(host='www.zhipin.comhttps', port=443): Max retries exceeded with url: //www.zhipin.com/gongsi/_zzz_c101281600_iy100504/ (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),))
